2024-06-18 08:01:41,343 ERROR app Thread-1 (process_request_thread) : Exception on /login [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 43, in login
    if current_user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-18 08:04:38,335 INFO app MainThread : MoodyWorld startup [in /home/myname/Workspace/Moody-World/app/__init__.py:44]
2024-06-18 08:04:44,001 ERROR app Thread-1 (process_request_thread) : Exception on /login [GET] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 43, in login
    if current_user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-18 08:04:49,756 ERROR app Thread-2 (process_request_thread) : Exception on /query [POST] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2024-06-18 09:05:02,399 INFO app MainThread : MoodyWorld startup [in /home/myname/Workspace/Moody-World/app/__init__.py:44]
2024-06-18 09:05:19,118 INFO app Thread-1 (process_request_thread) : Info level log [in /home/myname/Workspace/Moody-World/app/routes.py:14]
2024-06-18 09:05:19,118 WARNING app Thread-1 (process_request_thread) : Warning level log [in /home/myname/Workspace/Moody-World/app/routes.py:15]
2024-06-18 09:05:19,126 ERROR app Thread-1 (process_request_thread) : Exception on / [GET] [in /home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/app/routes.py", line 16, in home
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/templating.py", line 127, in _render
    app.update_template_context(context)
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask/app.py", line 493, in update_template_context
    context.update(self.ensure_sync(func)())
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 405, in _user_context_processor
    return dict(current_user=_get_user())
                             ^^^^^^^^^^^
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "/home/myname/Workspace/Moody-World/moody/lib/python3.12/site-packages/flask_login/login_manager.py", line 347, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
